version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ws2122-lspm:/ws2122-lspm/

    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
